<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SimpleInteractiveEngine\SimpleInteractiveEngine.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="testIcons\" />
  </ItemGroup>

  <ItemGroup>
    <None Update="testIcons\add_circle_32dp_2854C5_FILL0_wght400_GRAD0_opsz40.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="testIcons\apps_32dp_2854C5_FILL0_wght400_GRAD0_opsz40.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="testIcons\arrow_back_32dp_2854C5_FILL0_wght400_GRAD0_opsz40.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="testIcons\arrow_forward_32dp_2854C5_FILL0_wght400_GRAD0_opsz40.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="testIcons\cancel_32dp_2854C5_FILL0_wght400_GRAD0_opsz40.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="testIcons\check_box_outline_blank_32dp_2854C5_FILL0_wght400_GRAD0_opsz40.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="testIcons\check_circle_32dp_2854C5_FILL0_wght400_GRAD0_opsz40.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="testIcons\close_32dp_2854C5_FILL0_wght400_GRAD0_opsz40.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="testIcons\delete_32dp_2854C5_FILL0_wght400_GRAD0_opsz40.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="testIcons\home_32dp_2854C5_FILL0_wght400_GRAD0_opsz40.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="testIcons\login_32dp_2854C5_FILL0_wght400_GRAD0_opsz40.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="testIcons\search_32dp_2854C5_FILL0_wght400_GRAD0_opsz40.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="testIcons\settings_32dp_2854C5_FILL0_wght400_GRAD0_opsz40.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>